[tool.poetry]
name = "django-pet"
version = "0.1.0"
description = ""
authors = ["Segoletca <sergey.noskov.2001@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^5.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
